version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: vindow
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/vindow --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      ENVIRONMENT: development
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: vindow
      DATABASE_USER: root
      DATABASE_PASSWORD: 12345678
    depends_on:
      - mongo
